UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'logo-tagtik.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'hero-handshake-3d.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'icon-website.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'icon-branding.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'icon-content.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'icon-design.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'icon-marketing.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'icon-social-media.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'project-moujda.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'project-blendimmo.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'project-promotion.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'image.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'image copy.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'image copy copy.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'robot-3d-orange.png';
UPDATE media_library SET url = 'data:image/png;base64,W0RVTU1ZIEZJTEUgQ09OVEVOVF0=' WHERE filename = 'services-background.png';